---

- hosts: all
  become: true
  tasks:

  - name: Uninstall apache package (Ubuntu)
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: absent
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]