---

- hosts: all
  become: true
  pre_tasks:
  - name: Update cache
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: all
  become: true
  tasks:
    - name: Set authorised key for ansible user
      authorized_key:
        user: ideploysoftware
        key: "{{ lookup('file', '~/.ssh/ansible_rsa.pub') }}"

- hosts: web_servers
  become: true
  tasks:
    - name: install apache and php package (Ubuntu)
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: db_servers
  become: true
  tasks:
    - name: Install mariadb
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: file_servers
  become: true
  tasks:
    - name: Install samba
      apt:
        name: samba
        state: latest
      when: ansible_distribution in ["Ubuntu", "Debian"]
